$schema: http://json-schema.org/draft-07/schema#
$id: kvstore/zip
allOf:
- $ref: KvStore
- type: object
  properties:
    driver:
      const: zip
    zip_key_value_store:
      $ref: ContextResource
      description: |-
        Specifies or references a previously defined
        `Context.zip_key_value_store`.
    atomic:
      type: boolean
      default: true
      description: |-
        Support atomic multi-key transactions.  If set to ``false``, the
        transaction behavior matches that of the `kvstore/file` and
        `kvstore/gcs` drivers, which may be useful for testing purposes.
definitions:
  zip_key_value_store:
    $id: Context.zip_key_value_store
    description: |-
      Represents the in-zip key-value store.  If multiple `kvstore/zip`
      specifications reference the same `Context.zip_key_value_store`, they
      all refer to the same in-zip set of key/value pairs.
    type: object
  url:
    $id: KvStoreUrl/zip
    allOf:
    - $ref: KvStoreUrl
    - type: string
    type: string
    title: |
      :literal:`zip://` KvStore URL scheme
    description: |
      In-zip key-value stores may be specified using the custom
      :file:`zip://{path}` URL syntax.

      .. admonition:: Examples
         :class: example

         .. list-table::
            :header-rows: 1
            :widths: auto

            * - URL representation
              - JSON representation
            * - ``"zip://"``
              - ``{"driver": "zip"}``
            * - ``"zip://path/to/dataset"``
              - ``{"driver": "zip", "path": "path/to/dataset"}``
